version: '3'
services:
  wordpress:
    image: tfirdaus/wp-docklines:php7.2-apache
    depends_on:
      - database
    restart: on-failure
    ports:
      - ${WORDPRESS_SITE_PORT}:80
      - ${WORDPRESS_SITE_PORT_HTTPS}:443
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
  database:
    image: mysql:5.5
    volumes:
      - mysql:/var/lib/mysql
    restart: on-failure
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    restart: on-failure
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_HOST=${DB_HOST}
volumes:
  mysql:
