version: '3'
services:

  wordpress:
    build:
      context: .
    depends_on:
      - database
    restart: on-failure
    working_dir: ${WP_ROOT_DIR}
    ports:
      - "${WP_PUBLISHED_PORT}:80"
      - "${WP_PUBLISHED_PORT_HTTPS}:443"
    volumes:
      - "./wordpress:${WP_ROOT_DIR}"
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}

  database:
    image: ${DB_IMAGE}
    volumes:
      - mysql:/var/lib/mysql
    restart: on-failure
    ports:
      - "${DB_PUBLISHED_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    image: ${PMA_IMAGE}
    depends_on:
      - database
    restart: on-failure
    ports:
      - "${PMA_PUBLISHED_PORT}:80"
    environment:
      - PMA_HOST=${DB_HOST}

volumes:
  mysql:
