version: '3'
services:
  wordpress:
    build:
      context: .
      args:
        WORDPRESS_WORKDIR: ${WORDPRESS_WORKDIR}
    depends_on:
      - database
    restart: on-failure
    ports:
      - ${WORDPRESS_PORT}:80
      - ${WORDPRESS_PORT_HTTPS}:443
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${DATABASE_HOST}
      WORDPRESS_DB_NAME: ${DATABASE_NAME}
      WORDPRESS_DB_USER: ${DATABASE_USER}
      WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}
  database:
    image: mysql:5.5
    volumes:
      - mysql:/var/lib/mysql
    restart: on-failure
    ports:
      - ${DATABASE_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    restart: on-failure
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_HOST=${DATABASE_HOST}
volumes:
  mysql:
